version: 2

jobs:
    build_and_deploy: 
      working_directory: ~/repo
      docker:
        - image: cimg/node:16.13.2
      steps:
        - checkout
        - run:
            name: Update NPM
            command: "sudo npm install -g npm"
        - restore_cache:
            key: dependency-cache-{{ checksum "./frontend/package-lock.json" }}
        - run:
            name: Install Dependencies
            command: npm --prefix ./frontend install
        - save_cache:
            key: dependency-cache-{{ checksum "./frontend/package-lock.json" }}
            paths:
              - ./node_modules
        - run:
            name: Build React App
            command: npm --prefix ./frontend run build
        - save_cache:
            key: app-build-cache-{{ .Branch }}
            paths:
              - ./build
        - run:
            name: Pack UI to Backend
            command: |
              ls backend
              mkdir ~/repo/backend/static & mv ~/repo/frontend/build/* ~/repo/backend/static/
              ls backend
        - run:
            name: Deploy Main to Heroku
            command: |
              ls backend
              git config --global user.email "ayarhlaine.dev@gmail.com"
              git config --global user.name "Ayar Hlaine"
              git fetch
              git pull
              git add --all
              git commit -am "added ui to backend"
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  version: 2
  build-deploy:
    jobs:
        - build_and_deploy:
            filters:
              branches:
                  only: main # only run deploy-via-git job on main branch